global using System;
global using System.IO;
global using System.Reflection;
global using BoneLib;
global using MelonLoader;
global using TheJanitor.Melon;
global using BoneLib.BoneMenu;
global using BoneLib.BoneMenu.Elements;
global using BoneLib.Notifications;
global using SLZ.Marrow.Pool;
global using UnityEngine;
global using TheJanitor.Menu;
global using Object = UnityEngine.Object;